### ISSUE TITLE
<a href> </a> Anchor tags are not clickable (only detected as html link)

### ISSUE THREAD

**Issue by vgupt122** [evermeer/AttributedTextView#35]
In The below example Anchor tags are detected as html link but **not clickable** 
<a href=\'https://www.someurlink?username=12345'>Vivek Gupta</a>

I used like below

```
self.descriptionLabel.attributer = text.html.matchHashtags.makeInteract({ [weak self] (hashTag) in
            guard let slf = self else {return}
            slf.delegate?.tappedLink(string: hashTag)
            print(hashTag)
        }).matchMentions.makeInteract({ [weak self] (mentionsText) in
            guard let slf = self else {return}
            slf.delegate?.tappedLink(string: mentionsText)
            print(mentionsText)
        }).matchLinks.font(BrandManager.currentStyle.typography.boldFont(pts: 12)).makeInteract({ [weak self] (linkText) in
            guard let slf = self else {return}
            slf.delegate?.tappedLink(string: linkText)
            print(linkText)
        }).font(UIFont.regularFont(pts: 12)).setLinkColor(.red)
```

the 'text' variable has html string.

Has anyone got this issue.
Please help.

**Comment by evermeer** [comment]
Do you mean that the hashtags and mentions are working but the links not? Is your HTML using <a href markup? Then if so the matchLinks will only find thelinks inside your HTML tags. In your sample <a href='https://www.someurlink?username=12345'>Vivek Gupta</a> it will find the https://www.someurlink?username=12345 and make that clickable. but your html rendering will hide that part and only show Vivek Gupta and that will look like a link because of the HTML rendering, but you won't be able to click it. The .html will use the basic NSAttributedText functionality for parsing html to an NSAttributedTekst. I'm not sure if there is a way to find all links inside that parsed tekst. If you know what text would be inside the link, then you could search for that and make that clickable. So find Vivek Gupta and execute a .makeInteract on that.

**Comment by vgupt122** [comment]
Sure! I will try.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
